[build]
# Uncomment the relevant target for your chip
# target = "xtensa-esp32-espidf" # ESP32-WROOM32
# target = "riscv32imc-esp-espidf" # ESP32-C3
# target = "xtensa-esp32s2-espidf" # ESP32-S2
target = "xtensa-esp32s3-espidf" # ESP32-S3

rustflags = "--cfg espidf_time64"

[env]
# Uncomment the relevant MCU for your chip
# MCU = "esp32" # ESP32-WROOM32
# MCU = "esp32c3" # ESP32-C3
# MCU = "esp32s2" # ESP32-S2
MCU = "esp32s3" # ESP32-S3

ESP_IDF_PATH_ISSUES = "warn"
# Note: these variables are not used when using pio builder
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF stable (v5.4)
ESP_IDF_VERSION = "v5.4"
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF master (mainline)
# ESP_IDF_VERSION = { value = "master" }

[unstable]
build-std = ["std", "panic_abort"]
# build-std-features = ["panic_immediate_abort"] # Required for older ESP-IDF versions without a realpath implementation

[target.'cfg(any(target_arch = "xtensa", target_arch = "riscv32imc"))']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

# Disallow warnings when compiled in release (for GitHub sctions mainly)
[target.'cfg(not(debug_assertions)']
rustflags = ["-D", "warnings"]

[net]
git-fetch-with-cli = true
