[build]
rustflags = "--cfg espidf_time64"

# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
#target = "xtensa-esp32-espidf"
#target = "xtensa-esp32s2-espidf"
target = "xtensa-esp32s3-espidf"
#target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[unstable]

build-std = ["std", "panic_abort"]
# Required for older ESP-IDF versions without a realpath implementation.
# Enabling panic_immediate_abort may remove 100K+ from binary size but panic messages will not be printed.
#build-std-features = ["panic_immediate_abort"]

[env]
MCU = "esp32s3"
# Note: these variables are not used when using pio builder
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF stable (v5.1)
ESP_IDF_VERSION = "v5.1.1"
# Enables the esp-idf-sys "native" build feature (`cargo build --features native`) to build against ESP-IDF master (mainline)
#ESP_IDF_VERSION = { value = "master" }
ESP_IDF_PATH_ISSUES = 'warn'

[net]
git-fetch-with-cli = true